ifeq ($(BOOTLOADER_DEFCONFIG),)
$(error BOOTLOADER_DEFCONFIG must be set as environment variable)
endif

ifeq ($(INSTALLED_BOOTLOADER_TARGET),)
INSTALLED_BOOTLOADER_TARGET := $(PRODUCT_OUT)/lk.bin
endif


TARGET_BOOTABLE_SOURCE := bootable
TARGET_BOOTLOADER_SOURCE := $(TARGET_BOOTABLE_SOURCE)/bootloader
BOOTLOADER_BIN_PATH := $(TARGET_BOOTLOADER_SOURCE)/build-$(BOOTLOADER_DEFCONFIG)
BOOTLOADER_BIN := $(BOOTLOADER_BIN_PATH)/lk.bin
BOOTLOADER_CROSS_COMPILE_PATH := $(PWD)/$(TARGET_BOOTABLE_SOURCE)/toolchain/aarch64-elf-5.3.0-Linux-x86_64/bin/aarch64-elf-


ifeq ($(N_BOOTLOADER_BUILD_THREAD),)
N_BOOTLOADER_BUILD_THREAD := 8
endif

.PHONY: bootloader-distclean
bootloader-distclean:
	rm -rf $(BOOTLOADER_BIN_PATH)

.PHONY: bootloader
bootloader: $(INSTALLED_BOOTLOADER_TARGET)

$(BOOTLOADER_BIN): bootloader-distclean
	$(hide) echo "Building bootloader..."
	$(MAKE) -C $(TARGET_BOOTLOADER_SOURCE) $(BOOTLOADER_DEFCONFIG) ARCH_arm64_TOOLCHAIN_PREFIX=$(BOOTLOADER_CROSS_COMPILE_PATH) -j$(N_BOOTLOADER_BUILD_THREAD)

$(INSTALLED_BOOTLOADER_TARGET): $(BOOTLOADER_BIN) $(INSTALLED_BL2_TARGET)
	cp $(BOOTLOADER_BIN) $(INSTALLED_BOOTLOADER_TARGET)

